version: "2"
volumes:
  godata_server:
  godata_agent:

services:
  server:
    extends:
      file: ./stack/compose/services/gocd-server.yml
      service: server
    environment:
      GO_SERVER_SYSTEM_PROPERTIES: -Xmx4096m
    volumes:
      - godata_server:/godata
      - ./data/server/log:/var/log/go-server
      - ./stack/containers/server/config/cruise-config.xml:/etc/go/cruise-config.xml

  agent:
    extends:
      file: ./stack/compose/services/gocd-agent.yml
      service: agent
    environment:
      GO_SERVER_SYSTEM_PROPERTIES: -Xmx4096m
      GO_SERVER_URL: https://server:8154/go
    volumes:
      - godata_agent:/godata
    links:
      - server
