version: "2"
volumes:
  godata_server:
  godata_agent:

services:
  server:
    restart: always
    extends:
      file: ./stack/compose/services/gocd-server.yml
      service: server
    env_file:
      - go.env
    volumes:
      - godata_server:/godata

  agent:
    restart: always
    extends:
      file: ./stack/compose/services/gocd-agent.yml
      service: agent
    env_file:
      - go.env
    volumes:
      - godata_agent:/godata
    links:
      - server
