pipelines:
  pipe1:
    group: simple
    materials:
      mygit: {git: 'git@github.com:gregorskii/gocd-test.git'}
    stages:
    - build:
        jobs:
          build:
            tasks:
            - exec:
                arguments: [-c, echo "test"]
                attributes: null
                command: /bin/bash
