version: "2"
services:
  agent:
    build:
      context: ../../containers/agent
      args:
        GOCD_VERSION: ${GOCD_VERSION}
        GOCD_AGENT_CONTAINER: ${GOCD_AGENT_CONTAINER}
    image: gocd-agent:${GOCD_VERSION}
