version: "2"
services:
  agent:
    build:
      context: ../../containers/agent
      args:
        GOCD_VERSION: v${GOCD_VERSION}
        GOCD_AGENT_CONTAINER: ${GOCD_AGENT_CONTAINER}
    image: gocd-agent:v${GOCD_VERSION}
